init:
  - git config --global core.autocrlf true

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GRADLE_OPTS: -Dorg.gradle.daemon=false

cache:
  - C:\Users\appveyor\.gradle

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      ForEach ($file in Get-ChildItem '.\build\test-results\*.xml') {
        (New-Object 'System.Net.WebClient').UploadFile($url, $file)
      }
