name: Release plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build
      run: ./gradlew build

    - name: Publish to plugins.gradle.org
      run: |
        ./gradlew -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
                  -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} \
                  -Prelease=true \
                  publishPlugins
