name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build
      run: ./gradlew assemble testClasses

    - name: Test
      run: ./gradlew check

    - name: SonarQube analysis
      run: ./gradlew sonarqube
      if: github.ref == 'refs/heads/main'
      env:
        SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
